basic/controllers/CidadeController.php
<?php

namespace app\controllers;

use app\models\Cidade;
use app\models\Pessoa;
use yii\helpers\Json;

class CidadeController extends \yii\web\Controller
{
    public function actionProprietarios()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != NULL) {
                $cidade_id = $parents[0];
                $out = Pessoa::find()->where(['cidade_id' => $cidade_id])->select(['id', "nome as name"])->asArray()->all();

                return Json::encode(['output' => $out, 'selected' => '']);
            }
        }
        $out = Pessoa::find()->where(['cidade_id' => 1])->select(['id', 'nome as name'])->asArray()->all();
        return Json::encode(['output' => $out, 'selected' => '']);
    }

}

basic/controllers/EstadoController.php
<?php

namespace app\controllers;

use app\models\Cidade;
use yii\helpers\Json;

class EstadoController extends \yii\web\Controller
{
    public function actionCidades()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != NULL) {
                $estado_id = $parents[0];
                $out = Cidade::find()->where(['estado_id' => $estado_id])->select(['id', "nome as name"])->asArray()->all();

                return Json::encode(['output' => $out, 'selected' => '']);
            }
        }
        $out = Cidade::find()->where(['estado_id' => 1])->select(['id', 'nome as name'])->asArray()->all();
        return Json::encode(['output' => $out, 'selected' => '']);
    }

}

basic/controllers/Imovel2Controller.php
<?php

namespace app\controllers;

use app\models\Estado;
use Yii;
use app\models\Imovel;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ImovelController implements the CRUD actions for Imovel model.
 */
class Imovel2Controller extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Imovel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Imovel::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Imovel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Imovel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Imovel();
        $estados = Estado::find()->select(['id', 'nome as name'])->asArray()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'estados' => $estados,
        ]);
    }

    /**
     * Updates an existing Imovel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Imovel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Imovel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Imovel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Imovel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

basic/views/imovel2/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\depdrop\DepDrop;
use kartik\money\MaskMoney;

/* @var $this yii\web\View */
/* @var $model app\models\Imovel */
/* @var $form yii\widgets\ActiveForm */
/* @var $estados \app\models\Estado[] */

$estados = \yii\helpers\ArrayHelper::map($estados, 'id', 'name');

?>

<div class="imovel-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cep')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'estado_id')->dropDownList($estados); ?>

    <?= $form->field($model, 'cidade_id')->widget(DepDrop::classname(), [
        'type' => DepDrop::TYPE_SELECT2,
        'pluginOptions' => [
            'depends' => ['imovel-estado_id'],
            'placeholder' => 'Select a cidade...',
            'url' => Url::to(['estado/cidades'])
        ]
    ]);
    ?>

    <?= $form->field($model, 'pessoa_id')->widget(DepDrop::classname(), [
        'type' => DepDrop::TYPE_SELECT2,
        'pluginOptions' => [
            'depends' => ['imovel-cidade_id'],
            'placeholder' => 'Select a cidade...',
            'url' => Url::to(['cidade/proprietarios'])
        ]
    ]);
    ?>

    <?= $form->field($model, 'rua')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'complemento')->textInput(['maxlength' => true]) ?>

    <label for="valor"><?= $model->getAttributeLabel('valor') ?></label>
    <?php
    echo MaskMoney::widget([
        'name' => 'valor',
        'pluginOptions' => [
            'prefix' => 'R$ ',
            'thousands' => '.',
            'decimal' => ',',
            'precision' => 2
        ],
    ]) . '<br>';
    ?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/imovel2/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Imovel */

$this->title = 'Create Imovel';
$this->params['breadcrumbs'][] = ['label' => 'Imoveis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="imovel-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'estados' => $estados,
    ]) ?>

</div>

basic/views/imovel2/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Imoveis';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="imovel-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Imovel', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nome',
            [
                'attribute' => 'proprietario.'.\app\models\Pessoa::representingColumn(),
                'label' => 'Proprietário',
            ],
            'cep',
            'rua',
            [
                'attribute' => 'cidade.'.\app\models\Cidade::representingColumn(),
                'label' => 'Cidade',
            ],
            [
                'attribute' => 'estado.'.\app\models\Estado::representingColumn(),
                'label' => 'Estado',
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

basic/views/imovel2/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Imovel */

$this->title = 'Update Imovel: ' . $model->nome;
$this->params['breadcrumbs'][] = ['label' => 'Imoveis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nome, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="imovel-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/imovel2/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\extensions\Mask;

/* @var $this yii\web\View */
/* @var $model app\models\Imovel */

$this->title = $model->nome;
$this->params['breadcrumbs'][] = ['label' => 'Imoveis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="imovel-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nome',
            [
                'attribute' => 'proprietario.'.\app\models\Pessoa::representingColumn(),
                'label' => 'Proprietário',
            ],
            [
                'attribute' => 'cep',
                'value' => function($model){
                    if ($model->cep){
                        return Mask::cpf($model->cep, "#####-###");
                    }
                    return null;
                },
            ],
            'rua',
            [
                'attribute' => 'cidade.'.\app\models\Cidade::representingColumn(),
                'label' => 'Cidade',
            ],
            [
                'attribute' => 'estado.'.\app\models\Estado::representingColumn(),
                'label' => 'Estado',
            ],
        ],
    ]) ?>

</div>